theme: jekyll-theme-cayman
name: [null]
title: [The Uses Of MCMC And Nested Samplers]
description: [a collection of demonstrations of how off-the-shelf Python Markov Chain Monte Carlo and Nested Sampling algorithms can be used to analyse real world data sets]
